### ISSUE TITLE
Cannot run "run_random_agent.py"

### ISSUE THREAD

**Issue by HahmDY** [google-deepmind/android_env#200]
Hello.

I'm using m1 Mac and Android emulator version 32.1.12.0 and got error
`E0305 21:37:52.800976 7953584128 base_simulator.py:71] unknown option: -adb-path`
Maybe it's same with issue134 but emulator at https://developer.android.com/studio/emulator_archive was different with mine and couldn't use it. How can I update update emulator and resolve this issue?

Thank you.

**Comment by HahmDY** [comment]
Thank you! Now I could launch the emulator.
However, I have remaining issues. After the below message, the codes does not proceed to env.reset in my code.
Do you have any ideas?
`I0306 01:04:18.539759 8027246592 emulator_simulator.py:405] See the full emulator logs at '/tmp/android_env/simulator/simulator_instance_zklfmxen/emulator_output'`
```
def main(_):

  with loader.load(
      emulator_path=FLAGS.emulator_path,
      android_sdk_root=FLAGS.android_sdk_root,
      android_avd_home=FLAGS.android_avd_home,
      avd_name=FLAGS.avd_name,
      adb_path=FLAGS.adb_path,
      task_path=FLAGS.task_path,
      run_headless=FLAGS.run_headless) as env:

    action_spec = env.action_spec()

    def get_random_action() -> dict[str, np.ndarray]:
      """Returns a random AndroidEnv action."""
      action = {}
      for k, v in action_spec.items():
        if isinstance(v, specs.DiscreteArray):
          action[k] = np.random.randint(low=0, high=v.num_values, dtype=v.dtype)
        else:
          action[k] = np.random.random(size=v.shape).astype(v.dtype)
      return action

    _ = env.reset()

```

**Comment by kenjitoyama** [comment]
Can you paste the emulator logs? There's probably a problem booting it.

**Comment by HahmDY** [comment]
[emulator_output.txt](https://github.com/google-deepmind/android_env/files/14503386/emulator_output.txt)
Here it is.

**Comment by HahmDY** [comment]
Additionally, is there a way to downgrade android emulator in android studio to version 29.x.x? I could only find 34.1.18

**Comment by kenjitoyama** [comment]
Thanks for the info.

It seems that the emulator started successfully:

```
INFO    | Boot completed in 13676 ms
```

I'm not sure what the problem is, it looks like it is hanging after the emulator is up and running, maybe waiting on an `adb` command or something.

I don't have an ARM Apple to try this, but I'll see if I can reproduce this on Linux. I can update this bug once I find time to work on this.

I don't know how to downgrade the emulator, but it looks like it's not the culprit now since it seems to be starting well. You can run older Android APIs on recent versions of the Emulator. Do you have a particular reason to downgrade the Emulator?

**Comment by HahmDY** [comment]
Thank you, I'll try more to find the problem.
Maybe there are issues at coordinator in loader.py, while task_manager has returned but environment was not returned.

My coworker is using 29.x.x so I tried to reproduce the results.

**Comment by kenjitoyama** [comment]
This issue will be closed due to inactivity.
