### ISSUE TITLE
launching multiple ends

### ISSUE THREAD

**Issue by HahmDY** [google-deepmind/android_env#201]
Hi,
I'm trying to use multiple ends to collect more datas. For this, I declared multiple envs but failed with error. 
How can I solve this problem?
Thank you

I0313 01:13:47.496413 139673499981632 emulator_simulator.py:183] Initialized simulator with ADB server port 5037.
I0313 01:13:47.497501 139673499981632 emulator_launcher.py:99] Simulator local_tmp_dir: /tmp/android_env/simulator/simulator_instance_4w6cz6cc
I0313 01:13:47.499626 139673499981632 coordinator.py:89] simulator launching...
I0313 01:13:47.499822 139673499981632 coordinator.py:113] Simulator launch attempt 1 of 3
I0313 01:13:47.499963 139673499981632 emulator_simulator.py:239] Attempt 1 at launching the Android Emulator ('emulator-5554')
['/home/dongyoon/.local/share/android/sdk/emulator/emulator', '-adb-path', '/home/dongyoon/.local/share/android/sdk/platform-tools/adb', '-gpu', 'swiftshader_indirect', '-no-audio', '-show-kernel', '-verbose', '-avd', 'pixel_3_train_00', '-grpc', '8554', '-no-skin', '-no-window', '-ports', '35597,5555', '-no-snapshot']
I0313 01:13:47.500376 139673499981632 emulator_launcher.py:159] Emulator launch command: /home/dongyoon/.local/share/android/sdk/emulator/emulator -adb-path /home/dongyoon/.local/share/android/sdk/platform-tools/adb -gpu swiftshader_indirect -no-audio -show-kernel -verbose -avd pixel_3_train_00 -grpc 8554 -no-skin -no-window -ports 35597,5555 -no-snapshot
I0313 01:14:13.565765 139673499981632 emulator_simulator.py:405] See the full emulator logs at '/tmp/android_env/simulator/simulator_instance_4w6cz6cc/emulator_output'
I0313 01:14:14.148301 139673499981632 coordinator.py:92] simulator launched!!!
I0313 01:14:14.165779 139673499981632 environment.py:125] Resetting AndroidEnv...
E0313 01:14:14.166253 139673499981632 adb_log_stream.py:53] `stop_stream()` called before `get_stream_output()`. This violates the `LogStream` API.
I0313 01:14:28.249709 139673499981632 emulator_simulator.py:183] Initialized simulator with ADB server port 5039.
I0313 01:14:28.250501 139673499981632 emulator_launcher.py:99] Simulator local_tmp_dir: /tmp/android_env/simulator/simulator_instance_8qt_m8tt
I0313 01:14:28.251915 139673499981632 coordinator.py:89] simulator launching...
I0313 01:14:28.252094 139673499981632 coordinator.py:113] Simulator launch attempt 1 of 3
I0313 01:14:28.252236 139673499981632 emulator_simulator.py:239] Attempt 1 at launching the Android Emulator ('emulator-5556')
['/home/dongyoon/.local/share/android/sdk/emulator/emulator', '-adb-path', '/home/dongyoon/.local/share/android/sdk/platform-tools/adb', '-gpu', 'swiftshader_indirect', '-no-audio', '-show-kernel', '-verbose', '-avd', 'pixel_3_train_00', '-grpc', '34569', '-no-skin', '-no-window', '-ports', '37961,5557', '-no-snapshot']
I0313 01:14:28.252711 139673499981632 emulator_launcher.py:159] Emulator launch command: /home/dongyoon/.local/share/android/sdk/emulator/emulator -adb-path /home/dongyoon/.local/share/android/sdk/platform-tools/adb -gpu swiftshader_indirect -no-audio -show-kernel -verbose -avd pixel_3_train_00 -grpc 34569 -no-skin -no-window -ports 37961,5557 -no-snapshot
E0313 01:15:28.255342 139673499981632 emulator_simulator.py:368] Failed to connect to the emulator.
Traceback (most recent call last):
  File "/home/dongyoon/android_env/android_env/components/simulators/emulator/emulator_simulator.py", line 366, in _connect_to_emulator
    grpc.channel_ready_future(self._channel).result(timeout=60)
  File "/home/dongyoon/android_env/.eggs/grpcio-1.62.1-py3.10-linux-x86_64.egg/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/home/dongyoon/android_env/.eggs/grpcio-1.62.1-py3.10-linux-x86_64.egg/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
E0313 01:15:28.256708 139673499981632 base_simulator.py:71] INFO    | Using crash reporting configuration from environment variable: ANDROID_EMU_ENABLE_CRASH_REPORTING=1
E0313 01:15:28.256886 139673499981632 base_simulator.py:71] INFO    | Storing crashdata in: /tmp/android-dongyoon/emu-crash-34.1.19.db, detection is enabled for process: 869711
E0313 01:15:28.257060 139673499981632 base_simulator.py:71] INFO    | Android emulator version 34.1.19.0 (build_id 11525734) (CL:N/A)
E0313 01:15:28.257220 139673499981632 base_simulator.py:71] DEBUG   | Current emulator version 34.1.19 is the same as the required version 34.1.19.
E0313 01:15:28.257323 139673499981632 base_simulator.py:71] INFO    | Deleting /home/dongyoon/.android/avd/../avd/pixel_3_train_00.avd/bootcompleted.ini done
E0313 01:15:28.257415 139673499981632 base_simulator.py:71] INFO    | Found AVD name 'pixel_3_train_00'
E0313 01:15:28.257505 139673499981632 base_simulator.py:71] INFO    | Found AVD target architecture: x86_64

**Comment by kenjitoyama** [comment]
Hello @HahmDY , what do you mean by "multiple ends"? Do you mean "multiple envs" (environments)?

If yes, you'll need to make sure that each instance has its own emulator and that you do not create multiple adb servers. That is, you can reuse the same adb port (e.g. 5037) for all emulator instances otherwise a new adb server may interfere with other ones, and you may have problems talking to the emulators, which cause the environment to crash. You can read more about `adb` here: https://developer.android.com/tools/adb.

**Comment by kenjitoyama** [comment]
You cannot use the same AVD in multiple instantiations at the same time. You can copy it and launch it separately, but it's usually easier to create a new one.

You also cannot use the same [gRPC TCP port](https://github.com/google-deepmind/android_env/blob/18289e54bf93ffdc4d4655bff81a5c2723798bd4/android_env/components/config_classes.py#L115) for two emulator instances on the same machine. The only thing that should be shared is the adb server (usually on port 5037), but everything else should have its own settings.

**Comment by HahmDY** [comment]
Thank you! Now I could run multiple envs.
