### ISSUE TITLE
Cannot run run_randon_agent.py

### ISSUE THREAD

**Issue by LYXFOREVER** [google-deepmind/android_env#249]
I use the following command to run the code:

python run_random_agent.py --avd_name "AndroidWorldAvd" --android_avd_home "C:\Users\Dell\.android\avd" --android_sdk_root "C:\Users\Dell\AppData\Local\Android\Sdk" --emulator_path "C:\Users\Dell\AppData\Local\Android\Sdk\emulator\emulator" --adb_path "C:\Users\Dell\AppData\Local\Android\Sdk\platform-tools\adb" --num_steps 1000 --task_path "D:\code\androidWorld\android_env\tasks\Vokram\mdp_0000.textproto”

It will work at the beginning, but once the emulator started,emulator would quit right away.Then the process try to start the emulator again and same thing happens.After this the process ended, and I got this error:

E1112 10:50:50.045867 13404 base_simulator.py:81] DEBUG   | Concatenated backend parameters:  C:\Users\Dell\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe -adb-path C:\Users\Dell\AppData\Local\Android\Sdk\platform-tools\adb -gpu swangle_indirect -no-audio -show-kernel -verbose -avd AndroidWorldAvd -grpc 8554 -ports 53854,5555 -no-snapshot
Traceback (most recent call last):
  File "C:\Users\Dell\.conda\envs\android_world\Lib\shutil.py", line 632, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Another program is using this file, and the process cannot access it : '/tmp/android_env/simulator/simulator_instance_ar5jromf\\emulator_output'

I closed the android studio when running the code. I tried to open the emulator manualy in android studio and it work well. How can I solve this problem? Thank you!

**Comment by kenjitoyama** [comment]
Hi, we don't officially support Windows. Also, is this [AndroidWorld](https://github.com/google-research/android_world)? If yes, please open a bug there instead of AndroidEnv. Thanks!
@crawles FYI

**Comment by LYXFOREVER** [comment]
> Hi, we don't officially support Windows. Also, is this [AndroidWorld](https://github.com/google-research/android_world)? If yes, please open a bug there instead of AndroidEnv. Thanks! @crawles FYI

Sorry to disturb you！I didnt notice that. I will try it on Linux instead

**Comment by kenjitoyama** [comment]
No problem! Feel free to post your findings in the AndroidWorld repo page.
