### ISSUE TITLE
Just a general question: Can I connect to a real device?

### ISSUE THREAD

**Issue by flibbertigibbet-Y** [google-deepmind/android_env#252]

**Comment by kenjitoyama** [comment]
Hello @flibbertigibbet-Y , internally at Google we have a few ways to connect to real devices, but they're not in a state that we can readily share. This topic has come up before in issue #19  and https://github.com/google-research/android_world/issues/169, https://github.com/google-research/android_world/issues/121 (AndroidWorld is a project built on top of AndroidEnv). Unfortunately at the moment we are not planning to work on that. Cheers!

**Comment by kenjitoyama** [comment]
Hello @flibbertigibbet-Y , internally at Google we have a few ways to connect to real devices, but they're not in a state that we can readily share. This topic has come up before in issue #19  and https://github.com/google-research/android_world/issues/169, https://github.com/google-research/android_world/issues/121 (AndroidWorld is a project built on top of AndroidEnv). Unfortunately at the moment we are not planning to work on it, I hope you understand. Cheers!
